---
actions:
  to: skaffold.yaml
---
apiVersion: skaffold/v2beta6
kind: Config
profiles:
  - name: local
    build:
      artifacts:
        - image: {{artifactId}}
          jib:
            type: maven
            args:
              - -Plocal
      tagPolicy:
        sha256: {}
      local:
        push: true
    deploy:
      kustomize:
        paths:
          - kubernetes/overlays/local
