---
actions:
  to: kubernetes/overlays/base/kustomization.yaml
---
commonLabels:
  app.kubernetes.io/name: {{artifactId}}
resources:
  - github.com/kustomizations/spring-boot-web
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: app
    patch: |-
      - op: replace
        path: /metadata/name
        value: {{artifactId}}
  - target:
      version: v1
      kind: Service
      name: service
    patch: |-
      - op: replace
        path: /metadata/name
        value: {{artifactId}}     
